#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AndroidApp.Resource", IsApplication=true)]

namespace AndroidApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int Sensors = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int iot = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060014
			public const int Accept = 2131099668;
			
			// aapt resource value: 0x7f060011
			public const int BeginText = 2131099665;
			
			// aapt resource value: 0x7f06000d
			public const int Check = 2131099661;
			
			// aapt resource value: 0x7f060012
			public const int EndText = 2131099666;
			
			// aapt resource value: 0x7f06000b
			public const int HumidityText = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int HumidityValue = 2131099660;
			
			// aapt resource value: 0x7f060008
			public const int LightText = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int LightValue = 2131099657;
			
			// aapt resource value: 0x7f060010
			public const int LinearLayout1 = 2131099664;
			
			// aapt resource value: 0x7f060015
			public const int Lipa = 2131099669;
			
			// aapt resource value: 0x7f06000e
			public const int Plot = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int PlotLayout = 2131099663;
			
			// aapt resource value: 0x7f060005
			public const int SoundText = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int SoundValue = 2131099654;
			
			// aapt resource value: 0x7f060013
			public const int Spinner = 2131099667;
			
			// aapt resource value: 0x7f060002
			public const int TemperatureText = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int TemperatureValue = 2131099651;
			
			// aapt resource value: 0x7f060000
			public const int tableLayout = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int tableRow1 = 2131099649;
			
			// aapt resource value: 0x7f060004
			public const int tableRow2 = 2131099652;
			
			// aapt resource value: 0x7f060007
			public const int tableRow3 = 2131099655;
			
			// aapt resource value: 0x7f06000a
			public const int tableRow4 = 2131099658;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Plot = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
